SELECT BOOK_ID, b.AUTHOR_NAME, 
       DATE_FORMAT(a.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE FROM BOOK as a
JOIN AUTHOR as b on a.author_id = b.author_id
WHERE CATEGORY = '경제'
ORDER BY PUBLISHED_DATE